### ISSUE TITLE
BlobDownloadMiscError:  Miscellaneous error encountered while downloading one of the specified Azure Blob(s)

### ISSUE THREAD

**Issue by sinanakyazici** [Azure/azure-batch-samples#165]
I'm trying to run DoNetTutorial on my azure account. I have subscription.

It is giving this error while task being started. 
The pool was created.
The job was created.
The 3 nodes were created.

<img src='https://s31.postimg.org/4x8c8rror/Capture.png' border='0' alt='postimage'/>

But they failed. 

Can you help me ?

**Comment by mmacy** [comment]
Hi Sinan,

It is possible that this is a temporary error - can you please try running the sample again? If it still fails, please paste the contents of the console window after completion of the sample run.

In this sample, it is very possible for the start task to fail on one or two of the three nodes. This is because one node may start up and complete the tasks before the other two nodes have a chance to boot up completely. The sample then deletes the storage containers as part of its cleanup process, so when the slower-to-start nodes do eventually start, the container is not available for the start task to download the TaskApplication from the container (because the container was deleted).

You can use the [Batch Explorer](https://github.com/Azure/azure-batch-samples/tree/master/CSharp/BatchExplorer) to get more information on errors. This shows an example of a blob download error for a failed start task as it appears in Batch Explorer:

![image](https://cloud.githubusercontent.com/assets/13394541/17032815/01801796-4f30-11e6-830b-68901c2fe546.png)

Thanks,

--Marsh

**Comment by sinanakyazici** [comment]
Thanks Marsh. 

I solved my problem. It was about my storage. Probably the batch service cannot download aplication.exe because of not connected storage account. I created a batch service. I also created a storage service. But they weren't connected together. I deleted the batch service and storage service. I started to create them all over. It was an option about storage service while creating batch service. I selected related storage service while creating batch service.

<img src='https://s31.postimg.org/dcm0dy16j/Capture2.png' border='0' alt='postimage'/>

I created a storage service while creating batch service. It solved this problem.

**Comment by mmacy** [comment]
Glad to hear you got it working, Sinan!

I would like to point out, however, that task resource files (including start tasks) do not need to use a *linked* storage account. You must use a linked storage account for the [application packages](https://azure.microsoft.com/documentation/articles/batch-application-packages/) feature of Batch, but a standard, unlinked **General purpose** storage account is sufficient for your nodes to download start task resource files.

Is it possible that your old storage account was a **Blob storage** account? Batch does not currently support the Blob storage account type (which is the one that provides the hot/cold access tiers). The **General purpose** storage account includes blob storage support, and is compatible with Batch. If you were using a Blob storage account, the DotNetTutorial application would successfully create the containers and upload the resource files, but the start tasks would fail to download those resource files to the compute nodes when the nodes joined the pool. Using Batch Explorer, you'd see something similar to this error if you were trying to use a Blob storage account:

![image](https://cloud.githubusercontent.com/assets/13394541/17060461/fe2802de-4fde-11e6-8ba9-cb9b9438e67f.png)

Step 5 of [Create a storage account](https://azure.microsoft.com/documentation/articles/storage-create-storage-account/#create-a-storage-account) talks a bit about the differences between the two types of storage accounts.

Will now close this issue as it seems you've resolved the problem. Thanks for using Batch!

**Comment by sinanakyazici** [comment]
Thank you so much for your advices. I don't use application packages. Actually You said exactly what I want to do. I have a exe file and some DLLs. These are stored on blob storage with containers. I want to run code block in exe file on azure batch.  I have stream data to calculate, not a file.  My windows service needs to send the stream data to this exe file. I didn't understand how to use a resource file exactly.I researched about using stream file with resource files of tasks but I couldn't anything about this. So I tried to use storage account for my stream data. I will be so glad if you can help me for this. 

Best Regards...

**Comment by mmacy** [comment]
Hi Sinan,

I suggest that you post this question to the Azure Batch forum on MSDN. The Batch team monitors the forum closely, and can more thoroughly address the details of your use case. The Batch forum can be found here:

https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azurebatch
