### ISSUE TITLE
Cannot add Default Account Manager via Batch Explorer binaries compiled for Release

### ISSUE THREAD

**Issue by riverar** [Azure/azure-batch-samples#181]
1. Accounts, Add, Default Account Manager
2. Fill in fields with a,b,c,d.
3. Click OK button, note window does not dismiss
4. Retry steps with Debug binaries, note feature works as designed

**Comment by itowlson** [comment]
Thanks for reporting this. It seems to be related to the 'Optimize code' C# compiler option. When this option is turned on, account messages aren't reaching their MVVM Light registered handlers. Continuing to investigate.

**Comment by itowlson** [comment]
I think the problem is with MVVM Light message handlers implemented as closures.  When a message handler lambda closes over a local variable, C# compiles the lambda into a separate (anomymous) class and instantiates that class.  But MVVM Light holds only weak references, making the instance eligible for garbage collection.  Non-optimised builds hold an artificial reference which keeps the instance alive and allows the message to be delivered; in optimised builds, the instance gets GCed before the message reaches it.
