### ISSUE TITLE
Download stdout from jobs

### ISSUE THREAD

**Issue by liorbiu** [Azure/azure-batch-samples#197]
Hi,

I have task with 100 jobs and I want to download all the stdout.txt files.

I tried to do it using this python command : 

`txtfile = urllib2.urlopen('https://barilanbatchhpcuseast.eastus.batch.azure.com/jobs/Job1/tasks/task1_0_1/files/stdout.txt').read()`

But i got the following error : `urllib2.HTTPError: HTTP Error 400: A query parameter that's mandatory for this request is not specified`

What can be the problem?

**Comment by itowlson** [comment]
At minimum you are missing the apiversion query string (apiversion=20xx-yy-zz.maj.min).  You also need to authenticate by signing your request with the Batch account key, as your files are not publicly readable.  You may find it easier to do both of these by using the Batch client library for Python; otherwise, the REST API docs include info on API versions and on request signing.

**Comment by alfpark** [comment]
Closing as it looks like the issue has been resolved.
