### ISSUE TITLE
400 Client Error: The specified blob or block content is invalid

### ISSUE THREAD

**Issue by chanhou** [Azure/azure-batch-samples#43]
As I was using SAS to upload a 1Gb tsv file to a container, it fail. Is that any problem to do the upload or i am missing something need to do?

**Comment by alfpark** [comment]
Can you provide more context and/or output from the execution?

**Comment by chanhou** [comment]
I am transfer a tsv file to the blob and i disable the match md5 and using sas key which provided by the cup.

![screenshot from 2015-09-04 11 14 42](https://cloud.githubusercontent.com/assets/6903036/9675897/3b8a45ec-52f6-11e5-817a-a67733f2e236.png)

**Comment by alfpark** [comment]
There could be a lot of causes for this problem, but most likely the uncommitted block list on storage is in a state that will no longer work with the script. You will need to do one of the following: (1) perform a GetBlockList and commit the block list, then delete the blob, (2) create a dummy blob (can be of length zero) with the same blob name in the same container and transfer it using a non-blocked transfer, (3) wait 7 days for the uncommitted block list to garbage collect.

You can do either of (1) or (2) using the azure-storage python package, or you can perform (2) easily with a GUI-based tool like Azure Storage Explorer (windows-only unfortunately).

**Comment by chanhou** [comment]
Thanks for your reply.

Again I have another question.

The problem you said already fixed but other problem arise,

that is it always said that connection aborted, error(110,'connection timed out') when the progress around 96%, no matter I change the chunksizebytes and num of workers. 

How should I do for this problem?

**Comment by alfpark** [comment]
Unfortunately, that's an issue that will be hard to diagnose since that will depend on a variety of factors, including your connection quality and bandwidth, among other things. I would try to keep the chunksizebytes at default and decreasing the number of workers in the range of 2 to 8 to see if that alleviates your problem. Then you start increasing that number with something that's a good tradeoff between speed and consistency in transfer.

I am closing this issue now since the discussion is no longer related to the original issue.

**Comment by theodorDiaconu** [comment]
Bump I have the same exact issue. For a 120mb file.
